

services:
  angular:
    build:
      context: ./Angular_without_ssr
      dockerfile: Dockerfile
    image: angular:v1
    container_name: angular
    ports:
      - "4200:80"
    networks:
      - app-network

  angular-ssr:
    build:
      context: ./Angular_with_ssr
      dockerfile: Dockerfile
    image: angular-ssr:v1
    container_name: angular_ssr
    ports:
      - "4000:4000"
    networks:
      - app-network

  nestjs:
    build:
      context: ./Nestsjs_project
      dockerfile: Dockerfile
    image: nestjs:v1
    container_name: nestjs
    networks:
      - app-network

  express:
    build:
      context: ./ExpressJs
      dockerfile: Dockerfile
    image: express:v1
    container_name: express
    environment:
      DB_USER: system
      DB_PASSWORD: MySecurePass123
      DB_CONNECT_STRING: oracle-db/XE
    networks:
      - app-network

  nginx_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx:v1
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - angular
      - nestjs
      - express

#   oracle-db:
#     image: gvenzl/oracle-free:23.5-slim
#     container_name: oracle-db
#     ports:
#       - "1521:1521"      
#     environment:
#       - ORACLE_PWD=MySecurePass123    
#       - ORACLE_SID=XE                
#       - ORACLE_PDB=ORCLPDB1           
#       - ORACLE_CHARACTERSET=AL32UTF8  
#     volumes:
#       - oracle_data:/opt/oracle/oradata
#     healthcheck:
#       test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/$$ORACLE_PWD@localhost/XE || exit 1"]
#       interval: 30s
#       timeout: 10s
#       retries: 5

# volumes:
#   oracle_data:

networks:
  app-network:
    driver: bridge