version: '3.8'

services:
  angular:
    build:
      context: ./Angular
    container_name: angular
    networks:
      - app-network

  angular-ssr:
    build:
      context: ./angular-ssr
    container_name: angular_ssr
    networks:
      - app-network

  nestjs:
    build:
      context: ./nestjs
    container_name: nestjs
    networks:
      - app-network

  express:
    build:
      context: ./ExpressJs
    container_name: express
    networks:
      - app-network

  nginx_proxy:
    build:
      context: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    depends_on:
      - angular
      - nestjs
      - express

  oracle-db:
    image: gvenzl/oracle-free:23.5-slim
    # container-registry.oracle.com/database/standard 
    container_name: oracle-db
    ports:
      - "1521:1521"      
    environment:
      - ORACLE_PWD=MySecurePass123    
      - ORACLE_SID=XE                
      - ORACLE_PDB=ORCLPDB1           
      - ORACLE_CHARACTERSET=AL32UTF8  
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/$$ORACLE_PWD@localhost/XE || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle_data:

networks:
  app-network:
    driver: bridge